### ISSUE TITLE
Don't use nameFilter on tags or at least make it optional

### ISSUE THREAD

**Issue by jmartsch** [nbcommunication/WireMailgun#11]
Mailgun accepts strings which are much easier to read than a sanitized string.
See https://documentation.mailgun.com/en/latest/user_manual.html#tagging
So what do you think about removing the option to sanitize or at least make it optional?

**Comment by jmartsch** [comment]
Ok, I found out, that Mailgun accepts strings as tags, and displays them nicely on its analytics page:
![image](https://user-images.githubusercontent.com/551551/57929472-b6a11580-78b3-11e9-9cf3-aab119160685.png)
Bute there is a problem, if I try to delete these tags. They can't be removed.
A sanitized tag was removed without problems.

EDIT: Reported the issue to mailgun. Waiting for an answer.

**Comment by chriswthomson** [comment]
Hi @jmartsch,

I think the reason I used Sanitizer::nameFilter() in that way was it seemed to be the best way to adhere to the following:

https://documentation.mailgun.com/en/latest/user_manual.html#tagging - Note: Tags are case insensitive and should be ascii only. Maximum tag length is 128 characters.

Do you know of a better way to meet that requirement with Sanitizer? I'm pretty sure I spent a while looking into this and this seemed the best option. It allows for spaces, doesn't "beautify" the string and truncates to the 128 char max.

Cheers,

Chris

**Comment by jmartsch** [comment]
I totally oversaw the note. Maybe because it's standing out so much 🤣 
I will think about a better solution, but first have to wait for Mailgun's answer.
There is a problem deleting a tag which has a slash in it. But instead of removing the slash, it could be converted to a dash for better readability.
There seems to be no problem when deleting tags which contain a dash.

Compare "Newsletter Mai im Jahr 05/2019" to
![image](https://user-images.githubusercontent.com/551551/57932078-582b6580-78ba-11e9-84c2-758b8fc63734.png)
which is not very readable.

**Comment by chriswthomson** [comment]
I've reworked this to use filter_var() (and Sanitizer::truncate() for length). Pushed to master. Please let me know if that isn't working any better.

Cheers,

Chris
